### ISSUE TITLE
Create subnet in one of multiple blocks with the same name

### ISSUE THREAD

**Issue by fei-tkprice** [EfficientIP-Labs/terraform-provider-solidserver#18]
# Overview of Issue

The resource `solidserver_ip_subnet` does not look in additional blocks with the same name that have available address space.

## Desired Outcome

If there are multiple blocks with the same name the resource `solidserver_ip_subnet` will query each block for available address space for the new subnet.

## Example Configuration

```hcl
resource "solidserver_ip_subnet" "vnet_1" {
  space = "azure"
  block = solidserver_ip_subnet.block_1.name
  name = "vnet1"
  prefix_size = 26
  terminal = false
}

resource "solidserver_ip_subnet" "vnet_2" {
  space = "azure"
  block = solidserver_ip_subnet.block_1.name
  name = "vnet1"
  prefix_size = 26
  terminal = false
}

resource "solidserver_ip_subnet" "subnet_1" {
  space = "azure"
  block = solidserver_ip_subnet.vnet_1.name
  name = "subnet1"
  prefix_size = 27
  terminal = true
}

resource "solidserver_ip_subnet" "subnet_2" {
  space = "azure"
  block = solidserver_ip_subnet.vnet_1.name
  name = "subnet2"
  prefix_size = 27
  terminal = true
}

resource "solidserver_ip_subnet" "subnet_3" {
  space = "azure"
  block = solidserver_ip_subnet.vnet_2.name
  name = "subnet3"
  prefix_size = 27
  terminal = true
}
```

## Returned Error

![image](https://user-images.githubusercontent.com/58568143/217367698-60319bbe-7a4a-4e7f-88ad-4854a647f601.png)

## Environment Information

![image](https://user-images.githubusercontent.com/58568143/217367942-2e3abf22-9cbc-4f2c-a14e-f038567c5dad.png)

**Comment by alexissavin** [comment]
Hello,

I would not recommend to name blocks using identical names.
That is indeed possible in the IPAM, since the primary key is the prefix (ex: 10.0.0.0/8).
However naming blocks after the same name is something I have never observed.

Why would you do that ? Could you elaborate a use-case to discuss ?

For now, I'm not considering this request. From my point of view, subnets need to be created within an identified block.
I consider that block/subnet names should be unique within a given space.
Even if not enforced by the IPAM, I consider this as a common good practice.

Please let me know your feedback.

Kind regards

**Comment by IanTurtle** [comment]
Is it possible to reopen this issue? I have a use case where this would be handy

We have a situation where we deploy resources across multiple regions within a cloud, but have run out of space in one of the regions and need to allocate an additional CIDR. However the next contiguous block of IPs has already been allocated, so we end up in the following situation:

Original UK South - 10.1.0.0/16
Original UK West - 10.2.0.0/16
New UK South - 10.3.0.0/16

What I would like to be able to do is create two blocks called "UK South", and then leave it up to Terraform/EfficientIP to decide which block to create the subnet in, since we really don't care which one it creates it in. Rather than us having to call the REST API to determine which one is emptier.
