### ISSUE TITLE
Latest 1.1.21 release throws "checksum list has unexpected SHA-256 hash" errror

### ISSUE THREAD

**Issue by murathatipoglu** [EfficientIP-Labs/terraform-provider-solidserver#45]
Latest 1.1.21 version release earlier today causes the following error

│ Error: Failed to install provider
│ 
│ Error while installing efficientip-labs/solidserver v1.1.21: checksum list
│ has unexpected SHA-256 hash
│ 9a2b9fcbd41740b9820106f92b7ef6b42fdc2ff38e80034ab20d23318821e427 (expected
│ efbcab76085660b600b490c89cd8f786927b877dc1e53cb4d351c226adb3fa8b)

This made our pipelines start to fail because we use 

version = ">=1.1.15"

for solidserver provider. And it always tries to pull the latest version

@alexissavin

**Comment by alexissavin** [comment]
Sound like an issue with the registry I had previously, related to the binaries added to 1.1.21...
I will have to push a new release to fix it.

**Comment by alexissavin** [comment]
Sounds good with 1.1.22:
`terraform init
Initializing the backend...
Initializing provider plugins...
- Finding efficientip-labs/solidserver versions matching "1.1.22"...
- Installing efficientip-labs/solidserver v1.1.22...
- Installed efficientip-labs/solidserver v1.1.22 (self-signed, key ID ED9C3F7AA2D48731)
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!
`

Can you confirm it's ok on your side ?

Kind regards

**Comment by bestefreund** [comment]
We had the same Issue with `terraform init` and now I can confirm the issue has been gone with the new provider version `1.1.22`
