### ISSUE TITLE
solidserver_dns_rr AAAA

### ISSUE THREAD

**Issue by log4ever** [EfficientIP-Labs/terraform-provider-solidserver#9]
Hello there

In the context of IPv6, I notice that a `terraform delete` does not remove the AAAA record from efficientIP. There are cases where a supposedly missing AAAA record has to be created even though it already exists.

I'm using Version 1.1.14, darwin_amd64.

In case more information is needed, do not hesitate to contact me.

Sincerely log4ever

**Comment by alexissavin** [comment]
Hello,

Can you clarify your issue (what object are you deleting ? An IPv6 address or a DNS RR ?).
Also, can share a clear step to reproduce and ideally a sample terraform file that support your scenario ?

Not sure the issue comes from the provider, there are chances it comes from SOLIDserver itself.

Kind regards.

**Comment by log4ever** [comment]
Hi,

Below is the part that prompted me to open the issue.

```
resource "solidserver_dns_rr" "hostname" {
  dnsserver = var.dnsserver
  dnszone   = var.dnszone
  name      = "hostname.domain.tld"
  type      = "AAAA"
  value     = aws_instance.hostname.ipv6_addresses[0]
  ttl       = "300"
}
```

For the very first run, of course, no entry is set yet, so it is created as desired. With all subsequent runs, Terraform always wants to create one again, even though it exists. This results in the message that the entry already exists. Furthermore, the entry is not deleted during a `terraform destroy`.

**Comment by alexissavin** [comment]
Hello,

Well I think the issue is that the format of the IPv6 differs between the one stored in the tf.state and the one returned by SOLIDserver API (ex: 2001:42d0:0003:1b00:0212:0186:0033:0011).

Not sure how to fix that easily. It probably requires to use a CustomizeDiff for the RR value. I will try to have a look.

Meanwhile, you can try to submit a long IPv6 format.

Kind regards.

**Comment by alexissavin** [comment]
Definitely an issue, the format is supported for creating the RR, but existence check doesn't work, the short IPv6 notation must be converted to long when checking RR existence.

**Comment by alexissavin** [comment]
Latest commit in branch master should address the issue. Please confirm that it's working as expected on your side.
Many thanks for reporting the issue.

**Comment by log4ever** [comment]
Your last commit brought the solution. `terraform apply|delete` behaves with the AAAA records as expected.

Thanks for your support and have a nice weekend.
